export const shopConfig = {
  name: "Dynamite Roasting Coffee Bar",
  tagline: "7am - 6pm Everyday",
  logoPath: "/dynamite-logo.png",
  location: "Black Mountain, NC",
  phone: "(828) 357-8555",
  rewardDescription: "free drink",
  finePrint: "Beverages only. Card must be present at time of purchase.",
  stampsRequired: 10,
  colors: {
    background: "#FAF7F0",
    foreground: "#000000",
    headerBg: "#000000",
    headerText: "#F5C400",
    headerTextMuted: "rgba(245,196,0,0.55)",
    brandPrimary: "#F5C400",
    brandLight: "#F7CE33",
    brandDark: "#000000",
    cream: "#FAF7F0",
    stampEmpty: "#E8E3D8",
    stampFilled: "#F5C400",
    rewardBg: "#FFFBEE",
  },
} as const;
